[package]
name = "rpc_pool"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
dotenv.workspace = true
env_logger.workspace = true
solana-client.workspace = true
solana-sdk.workspace = true
futures.workspace = true

[[bin]]
name = "rpc_pool"
path = "src/main.rs"
