[package]
name = "ambush-takehome"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bincode = "1.3.3"
bs58 = "0.5.1"
clap = { version = "4.5.29", features = ["derive"] }
dotenv = "0.15.0"
solana-client = "2.1.13"
solana-sdk = "2.1.13"
