[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bincode.workspace = true
bs58.workspace = true
clap.workspace = true
dotenv.workspace = true
solana-client.workspace = true
solana-sdk.workspace = true
